start: _item*

_item: union | struct | group

?group: "group" name "{"  ((s2c_channels c2s_channels?) | (c2s_channels s2c_channels?)) "}"
?union: "union" name "{" fields "}"
?struct: "struct" name "{" fields "}"

fields: field (("," field)*) ","?
?field: name ":" fieldtype

?fieldtype: | array
           | (primitive | type)

?array: "[" (primitive | type) ";" length "]"

?s2c_channels: "s2c" "{" channels  "}"
?c2s_channels: "c2s" "{" channels  "}"

channels: channel (("," channel)*) ","?

?channel: name ":" "[" type ";" add_msgs ";" eventfd "]"

!name: CNAME
!type: CNAME


!length: INT

!primitive: "bool"
  | "i8"
  | "u8"
  | "i16"
  | "u16"
  | "i32"
  | "u32"
  | "f32"
  | "i64"
  | "u64"
  | "f64"


!bool: TRUE -> true
  | FALSE -> false

TRUE: "true"
FALSE: "false"

!eventfd: bool

!add_msgs: INT

%import common.CNAME -> CNAME
%import common.INT -> INT
%import common.WS
%import common.C_COMMENT -> C_COMMENT
%import common.CPP_COMMENT -> CPP_COMMENT

%ignore WS
%ignore C_COMMENT
%ignore CPP_COMMENT
